### PR TITLE
feat: show maximum number of ninjas that can enroll on an event

### PR DESCRIPTION
**Pull request by MarioRodrigues10**
Computer version:
image

Mobile Version:
image

### CODE REVIEW

**Review by Afonso-santos — COMMENTED** [review]
image

Well done Mário this is a feature is small but very helpful.  In the picture above you can see the icon isn't  align with the text , can you work on that ?

**Comment by MarioRodrigues10** [comment]
@Afonso-santos  i think that doesn't fix in the context of this PR , that fix should be that in another one.
What you think?

**Review by Afonso-santos — COMMENTED** [review]
:rocket:

**Review by Afonso-santos — APPROVED** [review]
Well done Mário !! :rocket:

**Pull request merged**
