### PR TITLE
Enhance set availability button

### PR DESCRIPTION
**Pull request by RuiL1904**
Before:
image

After:
image

### CODE REVIEW

**Comment by hgp22** [comment]
:heart:

**Comment by nelsonmestevao** [comment]
It should be only one button for confirming 👀 I think we should remove "Confirmar Inscrição"

**Review by MarioRodrigues10 — CHANGES_REQUESTED** [review]
The buttons aren't properly aligned in the mobile view.

image

**Comment by RuiL1904** [comment]
Fixed, @MarioRodrigues10!

**Review by MarioRodrigues10 — APPROVED** [review]
In my opinion, it would look nicer if both buttons were the same width because they would look more balanced. But anyway good job! :+1:

**Pull request merged**
